# Generated by Django 4.1 on 2022-09-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urecipe',
            name='recipe_image2',
        ),
    ]
