# Generated by Django 4.1 on 2022-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_urecipe_recipe_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urecipe',
            name='recipe_desc',
            field=models.CharField(max_length=250),
        ),
    ]
